version = 0.1
[default.deploy.parameters]
stack_name = "s3-deployment"
resolve_s3 = true
s3_prefix = "s3-deployment"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BucketName=\"media-host\" ExistingUserPoolId=\"ca-central-1_irvOYSe4M\""
image_repositories = []
